## Yield Data

In [1]:
import pandas as pd
import numpy as np
import altair as alt
import os


In [2]:
pwd


'/Users/katiechenning/Documents/umich/courses/si699'

In [4]:
vegetables = pd.read_csv('MichiganVegetableData.csv')

In [5]:
commodity_list1 = vegetables['Commodity'].unique().tolist()

In [6]:
for commodity in commodity_list1:
    commoditydf = vegetables[vegetables['Commodity'] == commodity]
    mi_commodity_YIELD = commoditydf[commoditydf['Data Item'].str.contains("YIELD")]
    year_length = len(mi_commodity_YIELD.Year.unique().tolist())
    if year_length > 15:
        print(commodity)

BEANS
CABBAGE
CARROTS
CELERY
ONIONS
PEPPERS
POTATOES
SQUASH
SWEET CORN
TOMATOES
ASPARAGUS
CUCUMBERS
PUMPKINS


## Cucumbers

In [7]:
mi_cucumbers = vegetables[vegetables['Commodity'] == 'CUCUMBERS']

In [8]:
mi_cucumbers['Data Item'].unique()

array(['CUCUMBERS - ACRES HARVESTED',
       'CUCUMBERS - OPERATIONS WITH AREA HARVESTED',
       'CUCUMBERS, FRESH MARKET - ACRES HARVESTED',
       'CUCUMBERS, FRESH MARKET - OPERATIONS WITH AREA HARVESTED',
       'CUCUMBERS, PROCESSING, PICKLES - ACRES HARVESTED',
       'CUCUMBERS, PROCESSING, PICKLES - OPERATIONS WITH AREA HARVESTED',
       'CUCUMBERS - PRICE RECEIVED, MEASURED IN $ / CWT',
       'CUCUMBERS, FRESH MARKET - PRICE RECEIVED, MEASURED IN $ / CWT',
       'CUCUMBERS, PROCESSING - PRICE RECEIVED, MEASURED IN $ / TON',
       'CUCUMBERS - ACRES PLANTED',
       'CUCUMBERS - PRODUCTION, MEASURED IN $',
       'CUCUMBERS - PRODUCTION, MEASURED IN CWT',
       'CUCUMBERS - YIELD, MEASURED IN CWT / ACRE',
       'CUCUMBERS, FRESH MARKET - PRODUCTION, MEASURED IN $',
       'CUCUMBERS, FRESH MARKET, UTILIZED - PRODUCTION, MEASURED IN CWT',
       'CUCUMBERS, NOT SOLD - PRODUCTION, MEASURED IN CWT',
       'CUCUMBERS, PROCESSING - PRODUCTION, MEASURED IN $',
       'CUCUMBE

In [9]:
mi_cucumbers_yield = mi_cucumbers[mi_cucumbers['Data Item'] 
                                                            == 'CUCUMBERS, PROCESSING, PICKLES - YIELD, MEASURED IN TONS / ACRE']

In [10]:
mi_cucumbers_yield.Year.unique()

array([2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005,
       2004, 2003, 2002, 2001, 2000, 1999, 1998])

In [11]:
#mi_cucumbers_yield

In [12]:
#cucumbers_ordered

In [13]:
cucumbers_yield_stripped_data = mi_cucumbers_yield[['Year', 'Value']]

In [14]:
cucumbers_yield_stripped_data['Value'] = pd.to_numeric(
    cucumbers_yield_stripped_data['Value'].str.replace(',', ''), errors='coerce')

<ipython-input-14-be056347f78d>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cucumbers_yield_stripped_data['Value'] = pd.to_numeric(


In [15]:
cucumbers_yield_stripped_data

Year  Value
9901   2015   5.90
10064  2014   6.10
10242  2013   5.80
10416  2012   5.40
10600  2011   5.60
10788  2010   6.40
10971  2009   5.80
11151  2008   6.20
11334  2007   5.30
11527  2006   5.20
11712  2005   4.80
11885  2004   5.00
12067  2003   5.40
12247  2002   4.60
12426  2001   4.25
12583  2000   6.00
12744  1999   6.00
12876  1998   5.00

## Pumpkin


In [16]:
mi_pumpkins = vegetables[vegetables['Commodity'] == 'PUMPKINS']

In [17]:
mi_pumpkins_yield = mi_pumpkins[mi_pumpkins['Data Item'] == 'PUMPKINS - YIELD, MEASURED IN CWT / ACRE']

In [18]:
mi_pumpkins_yield.Year.unique()

array([2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010,
       2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000])

In [19]:
pumpkins_yield_stripped_data = mi_pumpkins_yield[['Year', 'Value']]

In [20]:
pumpkins_yield_stripped_data

Year Value
8953   2020   160
9096   2019   150
9287   2018   190
9512   2017   155
9748   2016   155
9946   2015   155
10100  2014   160
10278  2013   155
10442  2012   150
10629  2011   145
10817  2010   140
11000  2009   110
11180  2008   145
11363  2007   115
11556  2006   150
11741  2005   145
11914  2004   140
12096  2003   140
12276  2002   120
12461  2001   120
12618  2000   160

## Cabbage

In [21]:
mi_cabbage = vegetables[vegetables['Commodity'] == 'CABBAGE']
#mi_cabbage['Data Item'].unique()

In [22]:
mi_cabbage_yield = mi_cabbage[mi_cabbage['Data Item'] == 'CABBAGE, FRESH MARKET - YIELD, MEASURED IN CWT / ACRE']

In [23]:
#mi_cabbage_yield

In [24]:
mi_cabbage_yield.Year.unique()

array([2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005,
       2004, 2003, 2002, 2001, 2000, 1999, 1998])

In [25]:
cabbage_yield_stripped_data = mi_cabbage_yield[['Year', 'Value']]
cabbage_yield_stripped_data

Year Value
9879   2015   290
10044  2014   270
10222  2013   230
10396  2012   250
10576  2011   230
10764  2010   280
10947  2009   260
11121  2008   280
11304  2007   320
11497  2006   340
11682  2005   360
11855  2004   270
12037  2003   320
12217  2002   300
12396  2001   320
12553  2000   250
12708  1999   280
12840  1998   260

## Potatoes

In [26]:
mi_potatoes = vegetables[vegetables['Commodity'] == 'POTATOES']

In [27]:
#mi_potatoes['Data Item'].unique()

In [28]:
potatoes_yield = mi_potatoes[mi_potatoes['Data Item'] == 'POTATOES - YIELD, MEASURED IN CWT / ACRE']

In [29]:
potatoes_yield.Year.unique()

array([2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011,
       2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000,
       1999, 1998, 1997, 1996, 1995, 1994, 1993, 1992, 1991, 1990, 1989,
       1988, 1987, 1986, 1985, 1984, 1983, 1982, 1981, 1980, 1979, 1978,
       1977, 1976, 1975, 1974, 1973, 1972, 1971, 1970, 1969, 1968, 1967,
       1966, 1965, 1964, 1963, 1962, 1961, 1960, 1959, 1958, 1957, 1956,
       1955, 1954, 1953, 1952, 1951, 1950, 1949, 1948, 1947, 1946, 1945,
       1944, 1943, 1942, 1941, 1940, 1939, 1938, 1937, 1936, 1935, 1934,
       1933, 1932, 1931, 1930, 1929, 1928, 1927, 1926, 1925, 1924, 1923,
       1922, 1921, 1920, 1919, 1918, 1917, 1916, 1915, 1914, 1913, 1912,
       1911, 1910, 1909, 1908, 1907, 1906, 1905, 1904, 1903, 1902, 1901,
       1900, 1899, 1898, 1897, 1896, 1895, 1894, 1893, 1892, 1891, 1890,
       1889, 1888, 1887, 1886, 1885, 1884, 1883, 1882, 1881, 1880, 1879,
       1878, 1877, 1876, 1875, 1874, 1873, 1872, 18

In [30]:
potatoes_year_only = potatoes_yield[potatoes_yield['Period'] == 'YEAR']

In [31]:
potatoes_yield_stripped_data = potatoes_year_only[['Year', 'Value']]

In [32]:
potatoes_yield_stripped_data

Year Value
8827   2021   420
8939   2020   390
9082   2019   420
9263   2018   380
9488   2017   370
...     ...   ...
14423  1870    52
14428  1869    62
14433  1868    53
14438  1867    62
14443  1866    60

[156 rows x 2 columns]

## Squash

In [33]:
mi_squash = vegetables[vegetables['Commodity'] == 'SQUASH']

In [34]:
squash_yield = mi_squash[mi_squash['Data Item'] == "SQUASH - YIELD, MEASURED IN CWT / ACRE"]

In [35]:
squash_yield.Year.unique()

array([2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010,
       2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000])

In [36]:
squash_yield_stripped_data = squash_yield[['Year', 'Value']]

In [37]:
squash_yield_stripped_data

Year Value
8964   2020   220
9107   2019   200
9298   2018   220
9523   2017   230
9759   2016   240
9951   2015   200
10105  2014   200
10283  2013   200
10447  2012   240
10635  2011   220
10823  2010   200
11006  2009   210
11186  2008   200
11369  2007   190
11562  2006   210
11747  2005   220
11920  2004   160
12102  2003   190
12282  2002   230
12473  2001   200
12630  2000   115

## Carrots

In [38]:
mi_carrots = vegetables[vegetables['Commodity'] == 'CARROTS']

In [39]:
#mi_carrots['Data Item'].unique()

In [40]:
carrots_yield = mi_carrots[mi_carrots['Data Item'] == "CARROTS, FRESH MARKET - YIELD, MEASURED IN CWT / ACRE"]

In [41]:
carrots_yield.Year.unique()

array([2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005,
       2004, 2003, 2002, 2001, 2000, 1999, 1998])

In [42]:
carrots_yield_stripped_data = carrots_yield[['Year', 'Value']]
carrots_yield_stripped_data

Year Value
9884   2015   240
10049  2014   310
10227  2013   290
10401  2012   280
10582  2011   260
10770  2010   250
10953  2009   270
11127  2008   290
11310  2007   300
11503  2006   320
11688  2005   360
11861  2004   310
12043  2003   350
12223  2002   330
12402  2001   350
12559  2000   280
12714  1999   280
12846  1998   290

## Celery

In [43]:
mi_celery = vegetables[vegetables['Commodity'] == 'CELERY']

In [44]:
#mi_celery['Data Item'].unique()

In [45]:
celery_yield = mi_celery[mi_celery['Data Item'] == "CELERY - YIELD, MEASURED IN CWT / ACRE"]

In [46]:
celery_yield.Year.unique()

array([2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008,
       2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999, 1998])

In [47]:
celery_yield_stripped_data = celery_yield[['Year', 'Value']]
celery_yield_stripped_data

Year Value
9227   2018   580
9452   2017   590
9684   2016   600
9891   2015   580
10054  2014   580
10232  2013   575
10406  2012   565
10588  2011   490
10776  2010   525
10959  2009   555
11139  2008   525
11322  2007   490
11515  2006   530
11700  2005   575
11873  2004   560
12055  2003   530
12235  2002   470
12414  2001   460
12571  2000   500
12732  1999   450
12864  1998   470

## Onions

In [48]:
mi_onions = vegetables[vegetables['Commodity'] == 'ONIONS']

In [49]:
#mi_onions['Data Item'].unique()

In [50]:
onion_yield = mi_onions[mi_onions['Data Item'] == "ONIONS, DRY, SUMMER, STORAGE - YIELD, MEASURED IN CWT / ACRE"]

In [51]:
onion_yield.Year.nunique()

18

In [52]:
onion_yield_stripped_data = onion_yield[['Year', 'Value']]
onion_yield_stripped_data

Year Value
9913   2015   330
10070  2014   370
10248  2013   300
10422  2012   230
10607  2011   240
10795  2010   220
10978  2009   350
11158  2008   280
11341  2007   260
11534  2006   250
11719  2005   260
11892  2004   290
12074  2003   320
12254  2002   230
12439  2001   270
12596  2000   270
12757  1999   270
12889  1998   260

In [53]:
onion_yield_stripped_data.to_csv('onions.csv', index=False)

## Peppers

In [54]:
mi_peppers = vegetables[vegetables['Commodity'] == 'PEPPERS']

In [55]:
#mi_peppers['Data Item'].unique()

In [56]:
pepper_yield = mi_peppers[mi_peppers['Data Item'] == "PEPPERS, BELL - YIELD, MEASURED IN CWT / ACRE"]

In [57]:
pepper_yield.Year.unique()

array([2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010,
       2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999,
       1998])

In [58]:
peppers_yield_stripped_data = pepper_yield[['Year', 'Value']]
peppers_yield_stripped_data

Year Value
8925   2020   230
9068   2019   255
9249   2018   240
9474   2017   255
9710   2016   260
9918   2015   280
10075  2014   260
10253  2013   250
10427  2012   260
10613  2011   270
10801  2010   230
10984  2009   240
11164  2008   250
11347  2007   260
11540  2006   270
11725  2005   280
11898  2004   290
12080  2003   250
12260  2002   250
12445  2001   260
12602  2000   220
12763  1999   200
12895  1998   200

In [59]:
peppers_yield_stripped_data.to_csv('peppers.csv', index=False)

## Corn

In [60]:
mi_corn = vegetables[vegetables['Commodity'] == 'SWEET CORN']

In [61]:
#mi_corn['Data Item'].unique()

In [62]:
corn_yield = mi_corn[mi_corn['Data Item'] == "SWEET CORN, FRESH MARKET - YIELD, MEASURED IN CWT / ACRE"]

In [63]:
corn_yield.Year.unique()

array([2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005,
       2004, 2003, 2002, 2001, 2000, 1999, 1998])

In [64]:
corn_yield_stripped_data = corn_yield[['Year', 'Value']]
corn_yield_stripped_data

Year Value
9956   2015   103
10110  2014    90
10288  2013   100
10452  2012   104
10641  2011    94
10829  2010   100
11012  2009   110
11192  2008    85
11375  2007    85
11568  2006   110
11753  2005   100
11926  2004    75
12108  2003    90
12288  2002    80
12479  2001    60
12636  2000    70
12779  1999    70
12911  1998    75

In [65]:
corn_yield_stripped_data.to_csv('corn.csv', index=False)

## Tomatoes

In [66]:
mi_tomatoes = vegetables[vegetables['Commodity'] == 'TOMATOES'] 

In [67]:
#mi_tomatoes['Data Item'].unique()

In [68]:
tomatoes_yield = mi_tomatoes[mi_tomatoes['Data Item'] == "TOMATOES, IN THE OPEN, FRESH MARKET - YIELD, MEASURED IN CWT / ACRE"]

In [69]:
tomatoes_yield.Year.unique()

array([2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005,
       2004, 2003, 2002, 2001, 2000, 1999, 1998])

In [70]:
tomatoes_yield_stripped_data = tomatoes_yield[['Year', 'Value']]
tomatoes_yield_stripped_data

Year Value
9961   2015   300
10115  2014   245
10293  2013   240
10457  2012   200
10647  2011   220
10835  2010   200
11018  2009   300
11198  2008   260
11381  2007   230
11574  2006   230
11759  2005   220
11932  2004   260
12114  2003   220
12294  2002   210
12485  2001   210
12642  2000   170
12785  1999   190
12917  1998   210

In [71]:
tomatoes_yield_stripped_data.to_csv('tomatoes.csv', index=False)

## Asparagus

In [72]:
mi_asparagus = vegetables[vegetables['Commodity'] == 'ASPARAGUS'] 

In [73]:
#mi_asparagus['Data Item'].unique()

In [74]:
asparagus_yield = mi_asparagus[mi_asparagus['Data Item'] == "ASPARAGUS - YIELD, MEASURED IN CWT / ACRE"]

In [75]:
asparagus_yield.Year.unique()

array([2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010,
       2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999,
       1998])

In [76]:
asparagus_yield_stripped_data = asparagus_yield[['Year', 'Value']]
asparagus_yield_stripped_data

Year Value
8881   2020    28
9024   2019    30
9183   2018    28
9337   2018    28
9408   2017    27
9561   2017    27
9639   2016    25
9860   2015    26
10028  2014    24
10207  2013    23
10381  2012    21
10558  2011    22
10746  2010    16
10872  2010    16
10929  2009    22
11103  2008    23
11286  2007    21
11473  2006    22
11658  2005    19
11831  2004    20
12013  2003    21
12193  2002    15
12372  2001    20
12529  2000    17
12684  1999    18
12816  1998    16

In [77]:
asparagus_yield_stripped_data.to_csv('asparagus.csv', index=False)

## Merging DataFrames

In [78]:
#cucumbers carrots onions corn tomatoes asparagus

In [79]:
cucumbers_yield_stripped_data['Crop'] = 'Cucumbers'

<ipython-input-79-e6774d2b0e9e>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cucumbers_yield_stripped_data['Crop'] = 'Cucumbers'


In [80]:
cucumbers_yield_stripped_data

Year  Value       Crop
9901   2015   5.90  Cucumbers
10064  2014   6.10  Cucumbers
10242  2013   5.80  Cucumbers
10416  2012   5.40  Cucumbers
10600  2011   5.60  Cucumbers
10788  2010   6.40  Cucumbers
10971  2009   5.80  Cucumbers
11151  2008   6.20  Cucumbers
11334  2007   5.30  Cucumbers
11527  2006   5.20  Cucumbers
11712  2005   4.80  Cucumbers
11885  2004   5.00  Cucumbers
12067  2003   5.40  Cucumbers
12247  2002   4.60  Cucumbers
12426  2001   4.25  Cucumbers
12583  2000   6.00  Cucumbers
12744  1999   6.00  Cucumbers
12876  1998   5.00  Cucumbers

In [81]:
carrots_yield_stripped_data ['Crop'] = 'Carrots'

<ipython-input-81-a4120013d2f4>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  carrots_yield_stripped_data ['Crop'] = 'Carrots'


In [82]:
cucumbers_and_carrots = cucumbers_yield_stripped_data.merge(carrots_yield_stripped_data, on='Year')

In [83]:
carrots_cucumbers = pd.concat([carrots_yield_stripped_data, cucumbers_yield_stripped_data])

In [84]:
onion_yield_stripped_data['Crop'] = 'Onions'

<ipython-input-84-08a6b29d4b04>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  onion_yield_stripped_data['Crop'] = 'Onions'


In [85]:
corn_yield_stripped_data['Crop'] = 'Corn'

<ipython-input-85-0324135952a8>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corn_yield_stripped_data['Crop'] = 'Corn'


In [86]:
asparagus_yield_stripped_data['Crop'] = 'Asparagus'

<ipython-input-86-d9ba4fe9a65b>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  asparagus_yield_stripped_data['Crop'] = 'Asparagus'


In [87]:
tomatoes_yield_stripped_data['Crop'] = 'Tomatoes'

<ipython-input-87-d3002c82ea85>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tomatoes_yield_stripped_data['Crop'] = 'Tomatoes'


In [88]:
squash_yield_stripped_data['Crop'] = 'Squash'

<ipython-input-88-c8501a222bda>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  squash_yield_stripped_data['Crop'] = 'Squash'


In [89]:
celery_yield_stripped_data['Crop'] = 'Celery'

<ipython-input-89-62f48d199caf>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  celery_yield_stripped_data['Crop'] = 'Celery'


In [90]:
peppers_yield_stripped_data['Crop'] = 'Peppers'

<ipython-input-90-a6820c68629c>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  peppers_yield_stripped_data['Crop'] = 'Peppers'


In [91]:
pumpkins_yield_stripped_data['Crop'] = 'Pumpkins'

<ipython-input-91-817cd81763bd>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pumpkins_yield_stripped_data['Crop'] = 'Pumpkins'


In [92]:
cabbage_yield_stripped_data['Crop'] = 'Cabbage'

<ipython-input-92-1681bf6066e7>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cabbage_yield_stripped_data['Crop'] = 'Cabbage'


In [93]:
carrots_cucumbers_asparagus = pd.concat([carrots_cucumbers, asparagus_yield_stripped_data])

In [94]:
carrots_cucumbers_asparagus

Year Value       Crop
9884   2015   240    Carrots
10049  2014   310    Carrots
10227  2013   290    Carrots
10401  2012   280    Carrots
10582  2011   260    Carrots
...     ...   ...        ...
12193  2002    15  Asparagus
12372  2001    20  Asparagus
12529  2000    17  Asparagus
12684  1999    18  Asparagus
12816  1998    16  Asparagus

[62 rows x 3 columns]

In [95]:
carrots_cucumbers_asparagus_tomatoes = pd.concat([carrots_cucumbers_asparagus, tomatoes_yield_stripped_data])

In [96]:
carrots_cucumbers_asparagus_tomatoes_onions = pd.concat([carrots_cucumbers_asparagus_tomatoes, onion_yield_stripped_data])

In [97]:
carrots_cucumbers_asparagus_tomatoes_onions.Crop.unique()

array(['Carrots', 'Cucumbers', 'Asparagus', 'Tomatoes', 'Onions'],
      dtype=object)

In [98]:
carrots_cucumbers_asparagus_tomatoes_onions_cabbage = pd.concat([carrots_cucumbers_asparagus_tomatoes_onions, cabbage_yield_stripped_data])

In [99]:
carrots_cucumbers_asparagus_tomatoes_onions_cabbage_pumpkins = pd.concat([carrots_cucumbers_asparagus_tomatoes_onions_cabbage, pumpkins_yield_stripped_data])

In [100]:
carrots_cucumbers_asparagus_tomatoes_onions_cabbage_pumpkins_squash = pd.concat([carrots_cucumbers_asparagus_tomatoes_onions_cabbage_pumpkins, squash_yield_stripped_data])

In [101]:
carrots_cucumbers_asparagus_tomatoes_onions_cabbage_pumpkins_squash_peppers = pd.concat([carrots_cucumbers_asparagus_tomatoes_onions_cabbage_pumpkins_squash, peppers_yield_stripped_data])

In [102]:
vegetable_yield = pd.concat([carrots_cucumbers_asparagus_tomatoes_onions_cabbage_pumpkins_squash_peppers, celery_yield_stripped_data])

In [103]:
from vega_datasets import data

source = data.stocks()

In [104]:
vegetable_yield

Year Value     Crop
9884   2015   240  Carrots
10049  2014   310  Carrots
10227  2013   290  Carrots
10401  2012   280  Carrots
10582  2011   260  Carrots
...     ...   ...      ...
12235  2002   470   Celery
12414  2001   460   Celery
12571  2000   500   Celery
12732  1999   450   Celery
12864  1998   470   Celery

[202 rows x 3 columns]

In [111]:
all_crops = alt.Chart(vegetable_yield).mark_line().encode(
    x='Year:N',
    y=alt.Y('Value:Q', title = 'Yield (CWT/ACRE)'),
    color='Crop',
    strokeDash='Crop',
)

In [106]:
asparagus_and_cucumbers = pd.concat([asparagus_yield_stripped_data, cucumbers_yield_stripped_data])

In [107]:
alt.Chart(asparagus_and_cucumbers).mark_line().encode(
    x='Year:N',
    y=alt.Y('Value:Q', title = 'Yield (CWT/ACRE)'),
    color='Crop',
    strokeDash='Crop',
)

alt.Chart(...)

In [109]:
crops=list(vegetable_yield['Crop'].unique())
crops.sort()
crops

['Asparagus',
 'Cabbage',
 'Carrots',
 'Celery',
 'Cucumbers',
 'Onions',
 'Peppers',
 'Pumpkins',
 'Squash',
 'Tomatoes']

In [148]:
selectCrops =alt.selection_multi(
    fields=['Crop'],
    init={"Crop":crops[0]},
    # notice the binding_radio
    bind=alt.binding_radio(options=crops, name="Crop"),#edit this line
    name="Crop"
)

SchemaValidationError: Invalid specification

        altair.vegalite.v4.schema.core.SelectionDef->0, validating 'type'

        'Asparagus' is not of type 'array'
        

In [113]:
radio_chart = all_crops.encode(
    opacity=alt.condition(selectCrops, alt.value(1.0), alt.value(0.0))
).add_selection(selectCrops)

In [114]:
radio_chart

alt.Chart(...)

In [115]:
 hover = alt.selection_single(
        fields=["Year"],
        nearest=True,
        on="mouseover",
        empty="none",
        clear="mouseout",
    )

In [139]:
selectors = all_crops.mark_point(filled = True, color = 'grey', size = 100).encode(
   x=alt.X(
        'Year'), 
 opacity=alt.condition(hover, alt.value(1), alt.value(0)))

In [140]:
selectors

alt.Chart(...)

In [145]:
tooltips = alt.Chart(vegetable_yield).mark_rule(strokeWidth=2,  color="grey").encode(
        x='Year:T',
        opacity=alt.condition(hover, alt.value(1), alt.value(0)),
    tooltip=['Value:Q','Year:N', 'Crop']
        
      
    ).add_selection(hover)

In [146]:
tooltips

alt.Chart(...)

In [147]:
alt.layer(radio_chart, tooltips, selectors)

alt.LayerChart(...)

In [176]:

base = (
        alt.Chart(vegetable_yield)
        .encode(
            x=alt.X(
                "Year:T",
                axis=alt.Axis(title=None, format=("%b %Y"), labelAngle=0, tickCount=6),
            ),
            y=alt.Y(
                "Value:Q", axis=alt.Axis(title='Yield (CWT/ACRE)')
            ),
        )
        .properties(width=500, height=400)
    )
  

In [177]:

radio_select = alt.selection_multi(
        fields=["Crop"], name="Crop", 
    )

crop_color_condition = alt.condition(
        radio_select, alt.Color("Crop:N", legend=None), alt.value("lightgrey")
    )

   

In [178]:

make_selector = (
        alt.Chart(vegetable_yield)
        .mark_circle(size=200)
        .encode(
            y=alt.Y("Crop:N", axis=alt.Axis(title="Pick Crop", titleFontSize=15)),
            color=crop_color_condition,
        )
        .add_selection(radio_select)
    )

   

highlight_crops = (
        base.mark_line(strokeWidth=2)
        .add_selection(radio_select)
        .encode(color=crop_color_condition)
    ).properties(title="Crop Yield by Year")

  

In [179]:
# nearest = alt.selection(
#         type="single", nearest=True, on="mouseover", fields=["Year"], empty="none"
#     )

#     # Transparent selectors across the chart. This is what tells us
#     # the x-value of the cursor
#     selectors = (
#         alt.Chart(vegetable_yield)
#         .mark_point()
#         .encode(
#             x="Year:T",
#             opacity=alt.value(0),
#         )
#         .add_selection(nearest)
#     )


    
# points = base.mark_point(size=5, dy=-10).encode(
#         opacity=alt.condition(nearest, alt.value(1), alt.value(0))
#     ).transform_filter(radio_select)
    

# tooltip_text = base.mark_text(
#         align="left",
#         dx=-60,
#         dy=-15,
#         fontSize=10,
#         fontWeight="bold",
#         lineBreak = "\n",
#     ).encode(
#         text=alt.condition(
#             nearest, 
#             alt.Text("Value:Q", format=".2f"), 
#             alt.value(" "),
 
#         ),
#     ).transform_filter(radio_select)


#     # Draw a rule at the location of the selection
# rules = (
#         alt.Chart(vegetable_yield)
#         .mark_rule(color="black", strokeWidth=2)
#         .encode(
#             x="Year:T",
#         )
#         .transform_filter(nearest)
#     )
 








In [180]:

hover = alt.selection_single(
        fields=["Year"],
        nearest=True,
        on="mouseover",
        empty="none",
        clear="mouseout",
    )
tooltips2 = alt.Chart(vegetable_yield).transform_pivot(
        "Crop", "Value", groupby=["Year"]
    ).mark_rule(strokeWidth=2,  color="red").encode(
        x='Year:T',
        opacity=alt.condition(hover, alt.value(1), alt.value(0)),
        tooltip=["Year", "Asparagus:Q", "Cabbage:Q", "Carrots:Q",
                 "Celery:Q",  "Cucumbers:Q", "Onions:Q", "Peppers:Q", "Pumpkins:Q", "Squash:Q", "Tomatoes:Q"]
    ).add_selection(hover)
   

In [181]:

(make_selector | alt.layer(highlight_crops, tooltips2 ))

alt.HConcatChart(...)